// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Breadcrumb: typeof import('./../src/components/Breadcrumb/index.vue')['default']
    CategoryItem: typeof import('./../src/components/Category/CategoryItem.vue')['default']
    Charts: typeof import('./../src/components/Charts/index.vue')['default']
    DataCard: typeof import('./../src/components/DataCard/index.vue')['default']
    GoodsItem: typeof import('./../src/components/Goods/GoodsItem.vue')['default']
    KolItem: typeof import('./../src/components/Kol/KolItem.vue')['default']
    KolTags: typeof import('./../src/components/KolTags/index.vue')['default']
    LinkItem: typeof import('./../src/components/LinkItem/index.vue')['default']
    LinkList: typeof import('./../src/components/LinkList/index.vue')['default']
    LoadMore: typeof import('./../src/components/LoadMore/index.vue')['default']
    RankList: typeof import('./../src/components/RankList/index.vue')['default']
    RankTabs: typeof import('./../src/components/RankTabs/index.vue')['default']
    SectionTitle: typeof import('./../src/components/SectionTitle/index.vue')['default']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TopTabs: typeof import('./../src/components/TopTabs/index.vue')['default']
    TrendChart: typeof import('./../src/components/TrendChart/index.vue')['default']
    TrendTip: typeof import('./../src/components/TrendTip/index.vue')['default']
  }
}

export { }
